# Generated by Django 5.1.9 on 2026-01-17 16:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('zone_condition', models.CharField(max_length=10, verbose_name='Zona')),
                ('description_condition', models.CharField(max_length=10, verbose_name='Descripción')),
                ('study_type', models.CharField(max_length=10, verbose_name='Tipo de estudio')),
                ('temperture_sup', models.SmallIntegerField(verbose_name='Temperatura superior')),
                ('temperture_inf', models.SmallIntegerField(verbose_name='Temperatura inferior')),
                ('percent_humidity_sup', models.SmallIntegerField(verbose_name='% de humedad relativa superior')),
                ('percent_humidity_inf', models.SmallIntegerField(verbose_name='% de humedad relativa inferior')),
                ('period_minimum_time', models.SmallIntegerField(verbose_name='Meses mínimos del Estudio')),
                ('detail_condition', models.TextField(blank=True, null=True, verbose_name='Detalle de la condición')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('condition_enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
                'db_table': 'Condition',
                'ordering': ['-zone_condition', '-version'],
            },
        ),
    ]
