# Generated by Django 5.1.9 on 2026-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ['zone_condition', '-version'], 'verbose_name': 'Condition', 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterField(
            model_name='condition',
            name='percent_humidity_inf',
            field=models.SmallIntegerField(verbose_name='% de HR inferior'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='percent_humidity_sup',
            field=models.SmallIntegerField(verbose_name='% de HR superior'),
        ),
    ]
