# Generated by Django 5.1.9 on 2026-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0002_alter_condition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='description_condition',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='period_minimum_time',
            field=models.SmallIntegerField(verbose_name='Meses del Estudio'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='study_type',
            field=models.CharField(max_length=20, verbose_name='Tipo de estudio'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='temperture_inf',
            field=models.SmallIntegerField(verbose_name='Temp. Inferior °C'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='temperture_sup',
            field=models.SmallIntegerField(verbose_name='Temp. Superior °C'),
        ),
    ]
