# Generated by Django 5.1.9 on 2026-01-17 02:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_product', models.CharField(max_length=25, verbose_name='Código')),
                ('description_product', models.CharField(max_length=200, verbose_name='Descripción Genérica')),
                ('pharma_form', models.CharField(blank=True, max_length=80, null=True, verbose_name='Forma Farmacéutica')),
                ('type_prod', models.CharField(max_length=100, verbose_name='Tipo de Producto')),
                ('brand_product', models.CharField(blank=True, default='No aplica', max_length=80, null=True, verbose_name='Nombre Comercial')),
                ('sanitary_license', models.CharField(max_length=80, verbose_name='Registro Sanitario')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('product_enabled', models.BooleanField(default=True, verbose_name='Activo')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ['-code_product', '-version'],
            },
        ),
    ]
