# Generated by Django 5.1.9 on 2026-01-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_product',
            field=models.ImageField(blank=True, null=True, upload_to='product/images/'),
        ),
    ]
