# Generated by Django 5.1.9 on 2026-01-22 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condition', '0003_alter_condition_description_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code_protocol', models.CharField(max_length=50, unique=True, verbose_name='Código de Protocolo')),
                ('study_type', models.CharField(max_length=100, verbose_name='Tipo de Estudio')),
                ('objective', models.TextField(verbose_name='Objetivo')),
                ('numbers_batch', models.PositiveIntegerField(verbose_name='Número de Lotes')),
                ('date_prepared', models.DateField(verbose_name='Fecha de Preparación')),
                ('date_approved', models.DateField(verbose_name='Fecha de Aprobación')),
                ('enabled_protocol', models.BooleanField(default=True, verbose_name='Protocolo Habilitado')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Versión')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='condition.condition', verbose_name='Condición')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols_prepared', to=settings.AUTH_USER_MODEL, verbose_name='Preparado por')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'db_table': 'Protocol',
                'ordering': ['code_protocol', '-version'],
            },
        ),
    ]
